/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLocationRouteImport } from './routes/api/location'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ItemItemIdRouteImport } from './routes/item.$itemId'
import { Route as PShareIdRouteImport } from './routes/p.$shareId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ItemItemIdPreviewRouteImport } from './routes/item.$itemId_.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationRoute = ApiLocationRouteImport.update({
  id: '/api/location',
  path: '/api/location',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemItemIdRoute = ItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const PShareIdRoute = PShareIdRouteImport.update({
  id: '/p/$shareId',
  path: '/p/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemItemIdPreviewRoute = ItemItemIdPreviewRouteImport.update({
  id: '/item/$itemId_/preview',
  path: '/item/$itemId/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/location': typeof ApiLocationRoute
  '/api/media': typeof ApiMediaRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/p/$shareId': typeof PShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/item/$itemId/preview': typeof ItemItemIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/location': typeof ApiLocationRoute
  '/api/media': typeof ApiMediaRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/p/$shareId': typeof PShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/item/$itemId/preview': typeof ItemItemIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/location': typeof ApiLocationRoute
  '/api/media': typeof ApiMediaRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/p/$shareId': typeof PShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/item/$itemId_/preview': typeof ItemItemIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/location'
    | '/api/media'
    | '/item/$itemId'
    | '/p/$shareId'
    | '/api/auth/$'
    | '/item/$itemId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/location'
    | '/api/media'
    | '/item/$itemId'
    | '/p/$shareId'
    | '/api/auth/$'
    | '/item/$itemId/preview'
  id:
    | '__root__'
    | '/'
    | '/api/location'
    | '/api/media'
    | '/item/$itemId'
    | '/p/$shareId'
    | '/api/auth/$'
    | '/item/$itemId_/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLocationRoute: typeof ApiLocationRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ItemItemIdRoute: typeof ItemItemIdRoute
  PShareIdRoute: typeof PShareIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ItemItemIdPreviewRoute: typeof ItemItemIdPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/location': {
      id: '/api/location'
      path: '/api/location'
      fullPath: '/api/location'
      preLoaderRoute: typeof ApiLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$itemId': {
      id: '/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shareId': {
      id: '/p/$shareId'
      path: '/p/$shareId'
      fullPath: '/p/$shareId'
      preLoaderRoute: typeof PShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$itemId_/preview': {
      id: '/item/$itemId_/preview'
      path: '/item/$itemId/preview'
      fullPath: '/item/$itemId/preview'
      preLoaderRoute: typeof ItemItemIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLocationRoute: ApiLocationRoute,
  ApiMediaRoute: ApiMediaRoute,
  ItemItemIdRoute: ItemItemIdRoute,
  PShareIdRoute: PShareIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ItemItemIdPreviewRoute: ItemItemIdPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
