version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - dependencies
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      dev-dependencies:
        dependency-type: 'development'
      production-dependencies:
        dependency-type: 'production'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: 'ci'
      include: 'scope'
